/* tslint:disable */
/* eslint-disable */
/**
 * Wardley Mapping Crew API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.8.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    HTTPValidationError,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    MapIdRequest,
    MapIdRequestFromJSON,
    MapIdRequestToJSON,
    OwmTextRequest,
    OwmTextRequestFromJSON,
    OwmTextRequestToJSON,
} from '../models';

export interface ConvertId2PngV2Convertid2pngPostRequest {
    mapIdRequest: MapIdRequest;
}

export interface ConvertOwm2JsonV2Convertowm2jsonPostRequest {
    owmTextRequest: OwmTextRequest;
}

export interface ConvertOwm2PngV2Convertowm2pngPostRequest {
    owmTextRequest: OwmTextRequest;
}

export interface ConvertOwm2SvgV2Convertowm2svgPostRequest {
    owmTextRequest: OwmTextRequest;
}

export interface ConvertOwm2TomlV2Convertowm2tomlPostRequest {
    owmTextRequest: OwmTextRequest;
}

export interface ConvertOwm2YamlV2Convertowm2yamlPostRequest {
    owmTextRequest: OwmTextRequest;
}

/**
 * 
 */
export class ConversionsApi extends runtime.BaseAPI {

    /**
     * API endpoint to generate a Wardley Map image from map_id.  :param request: The request body containing the map_id. :return: JSONResponse with the image URL.
     * Convert Id 2 Png
     */
    async convertId2PngV2Convertid2pngPostRaw(requestParameters: ConvertId2PngV2Convertid2pngPostRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<any>> {
        if (requestParameters.mapIdRequest === null || requestParameters.mapIdRequest === undefined) {
            throw new runtime.RequiredError('mapIdRequest','Required parameter requestParameters.mapIdRequest was null or undefined when calling convertId2PngV2Convertid2pngPost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/v2/convertid2png`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MapIdRequestToJSON(requestParameters.mapIdRequest),
        }, initOverrides);

        return new runtime.TextApiResponse(response) as any;
    }

    /**
     * API endpoint to generate a Wardley Map image from map_id.  :param request: The request body containing the map_id. :return: JSONResponse with the image URL.
     * Convert Id 2 Png
     */
    async convertId2PngV2Convertid2pngPost(requestParameters: ConvertId2PngV2Convertid2pngPostRequest, initOverrides?: RequestInit): Promise<any> {
        const response = await this.convertId2PngV2Convertid2pngPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * API endpoint to convert Wardley Map text to JSON format.  :param request: The request body containing the owmtext. :return: JSONResponse with the JSON representation of the Wardley Map.
     * Convert Owm 2 Json
     */
    async convertOwm2JsonV2Convertowm2jsonPostRaw(requestParameters: ConvertOwm2JsonV2Convertowm2jsonPostRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<any>> {
        if (requestParameters.owmTextRequest === null || requestParameters.owmTextRequest === undefined) {
            throw new runtime.RequiredError('owmTextRequest','Required parameter requestParameters.owmTextRequest was null or undefined when calling convertOwm2JsonV2Convertowm2jsonPost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/v2/convertowm2json`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: OwmTextRequestToJSON(requestParameters.owmTextRequest),
        }, initOverrides);

        return new runtime.TextApiResponse(response) as any;
    }

    /**
     * API endpoint to convert Wardley Map text to JSON format.  :param request: The request body containing the owmtext. :return: JSONResponse with the JSON representation of the Wardley Map.
     * Convert Owm 2 Json
     */
    async convertOwm2JsonV2Convertowm2jsonPost(requestParameters: ConvertOwm2JsonV2Convertowm2jsonPostRequest, initOverrides?: RequestInit): Promise<any> {
        const response = await this.convertOwm2JsonV2Convertowm2jsonPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * API endpoint to generate a Wardley Map image from text.  :param request: The request body containing the owmtext. :return: JSONResponse with the image URL.
     * Convert Owm 2 Png
     */
    async convertOwm2PngV2Convertowm2pngPostRaw(requestParameters: ConvertOwm2PngV2Convertowm2pngPostRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<any>> {
        if (requestParameters.owmTextRequest === null || requestParameters.owmTextRequest === undefined) {
            throw new runtime.RequiredError('owmTextRequest','Required parameter requestParameters.owmTextRequest was null or undefined when calling convertOwm2PngV2Convertowm2pngPost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/v2/convertowm2png`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: OwmTextRequestToJSON(requestParameters.owmTextRequest),
        }, initOverrides);

        return new runtime.TextApiResponse(response) as any;
    }

    /**
     * API endpoint to generate a Wardley Map image from text.  :param request: The request body containing the owmtext. :return: JSONResponse with the image URL.
     * Convert Owm 2 Png
     */
    async convertOwm2PngV2Convertowm2pngPost(requestParameters: ConvertOwm2PngV2Convertowm2pngPostRequest, initOverrides?: RequestInit): Promise<any> {
        const response = await this.convertOwm2PngV2Convertowm2pngPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * API endpoint to generate a Wardley Map SVG from text.  :param request: The request body containing the owmtext. :return: JSONResponse with the SVG image URL.
     * Convert Owm 2 Svg
     */
    async convertOwm2SvgV2Convertowm2svgPostRaw(requestParameters: ConvertOwm2SvgV2Convertowm2svgPostRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<any>> {
        if (requestParameters.owmTextRequest === null || requestParameters.owmTextRequest === undefined) {
            throw new runtime.RequiredError('owmTextRequest','Required parameter requestParameters.owmTextRequest was null or undefined when calling convertOwm2SvgV2Convertowm2svgPost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/v2/convertowm2svg`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: OwmTextRequestToJSON(requestParameters.owmTextRequest),
        }, initOverrides);

        return new runtime.TextApiResponse(response) as any;
    }

    /**
     * API endpoint to generate a Wardley Map SVG from text.  :param request: The request body containing the owmtext. :return: JSONResponse with the SVG image URL.
     * Convert Owm 2 Svg
     */
    async convertOwm2SvgV2Convertowm2svgPost(requestParameters: ConvertOwm2SvgV2Convertowm2svgPostRequest, initOverrides?: RequestInit): Promise<any> {
        const response = await this.convertOwm2SvgV2Convertowm2svgPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * API endpoint to convert Wardley Map text to TOML format.  :param request: The request body containing the owmtext. :return: JSONResponse with the TOML representation of the Wardley Map.
     * Convert Owm 2 Toml
     */
    async convertOwm2TomlV2Convertowm2tomlPostRaw(requestParameters: ConvertOwm2TomlV2Convertowm2tomlPostRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<any>> {
        if (requestParameters.owmTextRequest === null || requestParameters.owmTextRequest === undefined) {
            throw new runtime.RequiredError('owmTextRequest','Required parameter requestParameters.owmTextRequest was null or undefined when calling convertOwm2TomlV2Convertowm2tomlPost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/v2/convertowm2toml`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: OwmTextRequestToJSON(requestParameters.owmTextRequest),
        }, initOverrides);

        return new runtime.TextApiResponse(response) as any;
    }

    /**
     * API endpoint to convert Wardley Map text to TOML format.  :param request: The request body containing the owmtext. :return: JSONResponse with the TOML representation of the Wardley Map.
     * Convert Owm 2 Toml
     */
    async convertOwm2TomlV2Convertowm2tomlPost(requestParameters: ConvertOwm2TomlV2Convertowm2tomlPostRequest, initOverrides?: RequestInit): Promise<any> {
        const response = await this.convertOwm2TomlV2Convertowm2tomlPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * API endpoint to convert Wardley Map text to YAML format.  :param request: The request body containing the owmtext. :return: JSONResponse with the YAML representation of the Wardley Map.
     * Convert Owm 2 Yaml
     */
    async convertOwm2YamlV2Convertowm2yamlPostRaw(requestParameters: ConvertOwm2YamlV2Convertowm2yamlPostRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<any>> {
        if (requestParameters.owmTextRequest === null || requestParameters.owmTextRequest === undefined) {
            throw new runtime.RequiredError('owmTextRequest','Required parameter requestParameters.owmTextRequest was null or undefined when calling convertOwm2YamlV2Convertowm2yamlPost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/v2/convertowm2yaml`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: OwmTextRequestToJSON(requestParameters.owmTextRequest),
        }, initOverrides);

        return new runtime.TextApiResponse(response) as any;
    }

    /**
     * API endpoint to convert Wardley Map text to YAML format.  :param request: The request body containing the owmtext. :return: JSONResponse with the YAML representation of the Wardley Map.
     * Convert Owm 2 Yaml
     */
    async convertOwm2YamlV2Convertowm2yamlPost(requestParameters: ConvertOwm2YamlV2Convertowm2yamlPostRequest, initOverrides?: RequestInit): Promise<any> {
        const response = await this.convertOwm2YamlV2Convertowm2yamlPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
