/* tslint:disable */
/* eslint-disable */
/**
 * Wardley Mapping Crew API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.8.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ComponentRequest
 */
export interface ComponentRequest {
    /**
     * 
     * @type {string}
     * @memberof ComponentRequest
     */
    mapId: string;
    /**
     * 
     * @type {string}
     * @memberof ComponentRequest
     */
    name: string;
}

export function ComponentRequestFromJSON(json: any): ComponentRequest {
    return ComponentRequestFromJSONTyped(json, false);
}

export function ComponentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComponentRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'mapId': json['map_id'],
        'name': json['name'],
    };
}

export function ComponentRequestToJSON(value?: ComponentRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'map_id': value.mapId,
        'name': value.name,
    };
}

