/* tslint:disable */
/* eslint-disable */
/**
 * Wardley Mapping Crew API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.8.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MapIdRequest
 */
export interface MapIdRequest {
    /**
     * 
     * @type {string}
     * @memberof MapIdRequest
     */
    mapId: string;
}

export function MapIdRequestFromJSON(json: any): MapIdRequest {
    return MapIdRequestFromJSONTyped(json, false);
}

export function MapIdRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MapIdRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'mapId': json['map_id'],
    };
}

export function MapIdRequestToJSON(value?: MapIdRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'map_id': value.mapId,
    };
}

