/* tslint:disable */
/* eslint-disable */
/**
 * Wardley Mapping Crew API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.8.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OwmTextRequest
 */
export interface OwmTextRequest {
    /**
     * 
     * @type {string}
     * @memberof OwmTextRequest
     */
    owmtext: string;
}

export function OwmTextRequestFromJSON(json: any): OwmTextRequest {
    return OwmTextRequestFromJSONTyped(json, false);
}

export function OwmTextRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): OwmTextRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'owmtext': json['owmtext'],
    };
}

export function OwmTextRequestToJSON(value?: OwmTextRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'owmtext': value.owmtext,
    };
}

