/* tslint:disable */
/* eslint-disable */
/**
 * Wardley Mapping Crew API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.8.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SearchComponentRequest
 */
export interface SearchComponentRequest {
    /**
     * 
     * @type {string}
     * @memberof SearchComponentRequest
     */
    mapId: string;
    /**
     * 
     * @type {string}
     * @memberof SearchComponentRequest
     */
    searchTerm: string;
}

export function SearchComponentRequestFromJSON(json: any): SearchComponentRequest {
    return SearchComponentRequestFromJSONTyped(json, false);
}

export function SearchComponentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchComponentRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'mapId': json['map_id'],
        'searchTerm': json['search_term'],
    };
}

export function SearchComponentRequestToJSON(value?: SearchComponentRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'map_id': value.mapId,
        'search_term': value.searchTerm,
    };
}

